#version: '3.3'
services:
  rss-watch:
    image: docker.io/library/rss-watch:latest
    container_name: rss-watch
    hostname: rss-watch
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30m
    restart: always
    volumes:
      - $PWD/config:/config
      - $PWD/data:/data
    build:
      dockerfile: Dockerfile
